### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by TheNimbleNinja** [KenyMylankca/EnhancedArmaments#15]
https://gist.github.com/TheNimbleNinja/e9ebd16ed55895a1e05fbb940e899f7f
crash with the mod

**Comment by KenyMylankca** [comment]
when did this crash happen?
does it happen multiple times or only 1 time?
which mod it crashes with?
answer these questions first, then i may be able to understand what's going on.
i'm not a god.

**Comment by Clinkr1000** [comment]
im also having this issue. it is most likely caused by trying to swhow an invalid tooltip for an item. for me it was a piece of armor.
