### ISSUE TITLE
Using weapon with chained attribute causes server to crash

### ISSUE THREAD

**Issue by thunderwolf66102** [KenyMylankca/EnhancedArmaments#17]
Tested with two different weapons, one bow and one sword.

[log snippet.txt](https://github.com/KenyMylankca/EnhancedArmaments/files/2719112/log.snippet.txt)

**Comment by KenyMylankca** [comment]
"chained" ? this is NOT Levels's github, this is Enhanced Armaments's github, **[which is this](https://minecraft.curseforge.com/projects/enhanced-armaments)**
Use Enhanced Armaments or Levels, not both.
