### ISSUE TITLE
Client Crash - 

### ISSUE THREAD

**Issue by MokahTGS** [KenyMylankca/EnhancedArmaments#24]
Crash Log: https://paste.dimdev.org/obehemesep.mccrash

Full Mod List: https://pastebin.com/1yuCWnCg
MC 1.12.2
Forge 2836
EnhancedArmaments-1.3.15

Client Crashed but no crash on Server.

**Comment by KenyMylankca** [comment]
did it happen only once or does it happen always when do something?

**Comment by MokahTGS** [comment]
Consistently when using tinkers tools, oddly enough.

**Comment by KenyMylankca** [comment]
does it still happen on Forge 2838 with the newest TC?

**Comment by KenyMylankca** [comment]
i made enough debugging to reproduce this. please report again if anyone has this problem again.
