### ISSUE TITLE
Single player crash

### ISSUE THREAD

**Issue by EightBlade** [KenyMylankca/EnhancedArmaments#27]
https://paste.dimdev.org/rafaziboqa.mccrash

I get this crash whenever I try to enter my single player world. I have no idea what's causing it, though.

**Comment by KenyMylankca** [comment]
looks like your world is corrupted by something. sadly nothing to do. if u want to play in your world, remove Enhanced Armaments, load your world, play a bit(about 10 mins like u do everything) then put Enhanced Armaments again and try to load it. if it crashes again, nothing to do; create new world... and i don't know which mod or what Minecraft bug causes that corruption..
