### ISSUE TITLE
No Attribute

### ISSUE THREAD

**Issue by Ozvald-MC** [KenyMylankca/EnhancedArmaments#28]
Hello, when I make a new weapon, it has a rarity, but no matter how rare it is, it does not have a random attribute. I can give him bonuses with the level of the weapon, but I never have attributes. Whatever the version of the mod. I do not know how to solve this problem. I even tried using the mod alone. Do you know where this can come from? (sorry for my English i'm french)

**Comment by KenyMylankca** [comment]
What version? 1.12.2?
The rarity only effects the weapons attack damage or the armors armor rate or the bows power rate. It will not gain a random attribute as you use it. As you use it, it gains experience and gets tokens so you can use the tokens to level up the abilities. It's how it works.
