### ISSUE TITLE
I can't use Token

### ISSUE THREAD

**Issue by Serviettesky** [KenyMylankca/EnhancedArmaments#29]
Hello hello, 
I am currently building a server pvp / rpg and I'm falling in love with your mod that is great for my idea but unfortunately I have a small problem, I install your super mod that works good. but I meet a small problem ... I wanted to test the different capacity so I do / addlevel 100 to have the max of point, but the when I open the weapon modification menu with '' K '' , the menu does not open a problem, but here I can not use the token to choose the abilities. I do not know that I made the order to have the levels ????

Thank you in advance for your help, Jordy Vagnieres

**Comment by KenyMylankca** [comment]
tell me what version u are using first. minecraft and mod and forge. and the modlist

**Comment by Serviettesky** [comment]
I m in Forge 1.12.2 2838, Minecracft is in 1.12.2

modlist : Rpg Hub, Baubles, Better Crates, Blur, Bountiful+Baubles, Creative Core, Custom NPC, Doggy  Talents, Enhanced Armaments, Extra Alchemy, Furniture, Hammmer Core, Hearthstone Mod, IGCM, Improvable Skill 3, JEI, Mo Bend, Neat, Pendant of Life, Playeableitems, Rustic, Serviettesky Mod, Switchbow, Tool Belt, Varied Commodities, Vies Craft, Worldedit, World Protector, Xaeros minimap / Worldmap. 

All mod is in 1.12.2

**Comment by KenyMylankca** [comment]
try with forge 2847 then report the result again.

**Comment by KenyMylankca** [comment]
and remove your configs & options.txt folder&files before launching, and in a new world.

**Comment by Serviettesky** [comment]
Hmmm i foret to say it for an Multiplayer Server,   okay i reinstall the server on 2847 but i don't have understand ''remove your configs & options.txt folder&files before launching, and in a new world.''   i can't reaload the map, i have more 30day of build ^^. I can try on single player ?

**Comment by KenyMylankca** [comment]
dafuq? the server you are in doesn't have Enhanced Armaments mod???

**Comment by KenyMylankca** [comment]
and i don't say remove your world, just have a try in a new one.

**Comment by Serviettesky** [comment]
no i have instal Enhanced Armaments on my client and Server side.

**Comment by Serviettesky** [comment]
okay i try install forge 2847 and a new world

**Comment by KenyMylankca** [comment]
so can u please try it on a brand new server and client? new world, new configs folder(by removing/moving the old one) and new options.txt files.

**Comment by Serviettesky** [comment]
okay i have juste test to creat an new wolrd in solo, the mod work perfect... withe 1.12.2 2838...

Creat an new world in server... hard i don't want lose my actual map

**Comment by KenyMylankca** [comment]
i recommend u using latest forge for 1.12.2

**Comment by Serviettesky** [comment]
Okay in confirm, i have install 1.12.2 2847 server and client, all work perfect on multi server !!! thanks you so much the mod is so cool and thank for the quickly answer your Top !!!!
