### ISSUE TITLE
Crashing upon hitting enemy with config'ed Yoyo (from Tinker yoyos) (null hand error)

### ISSUE THREAD

**Issue by PhantomARC** [KenyMylankca/EnhancedArmaments#32]
[crash-2020-04-08_11.53.11-server.txt](https://github.com/KenyMylankca/EnhancedArmaments/files/4452337/crash-2020-04-08_11.53.11-server.txt)
 It seems that when I hit an enemy upon world load with an enhanced armament, the game crashes saying that I killed something barehanded, unable to apply the attribute to the null weapon.

**Comment by PhantomARC** [comment]
[crash-2020-04-08_12.43.05-server.txt](https://github.com/KenyMylankca/EnhancedArmaments/files/4452501/crash-2020-04-08_12.43.05-server.txt)
It also seems that when I hit an enemy with a ranged weapon from Tinker's, I get an array out of bound : 0 error, not sure if these are related.

**Comment by KenyMylankca** [comment]
prolly some mods mess up the hands queue used in attacking.
whatever, i can't fix it unless u find actually what mod causing the crash in a constant situation that happens everytime. so just tell me what mod(s) causing the crash with the action you do, then i can fix it. also, reproduce it in a new world.
second crash could be related, as i said, something messing up the hands queue. it's not EA's fault. it just checks the hands and applies the item in the hand
