### ISSUE TITLE
Not Working With Tinker's Construct

### ISSUE THREAD

**Issue by ghost** [KenyMylankca/EnhancedArmaments#33]
On 1.12.2 mod doesen't work with Tinker's Construct.

**Comment by JuanLeGuetteur** [comment]
Indeed, if a patch exists I haven't found it, maybe the mod author could fix that, that would be awsome. It works with the armory exmpansion of TC tho.

**Comment by KenyMylankca** [comment]
looks like you guys didn't read the mod page info.
