### ISSUE TITLE
How to add weapons to the whitelist

### ISSUE THREAD

**Issue by ainlzj** [KenyMylankca/EnhancedArmaments#36]
How to add weapons to the whitelist Can a tutorial be given?
Is it possible to add it directly in the game?

**Comment by KenyMylankca** [comment]
just read the main config file so you will know how to do it.
no you can't add it directly in the game.

**Comment by ainlzj** [comment]
I'm sorry. I did my best    
 # This is an extra item list to add custom support for such modded items. Be careful on this, it may crash if the item can't be enhanced. Style should be 'modid:item'. 
    # Example: tconstruct:broadsword
    S:extraItems <
     >
The generated file does not take effect

**Comment by KenyMylankca** [comment]
so what's the problem?

**Comment by ainlzj** [comment]
Add other module weapons that are not supported

**Comment by KenyMylankca** [comment]
show me what you tried and didn't work.

**Comment by ainlzj** [comment]
.minecraft\config\Enhanced Armaments\main.cfg

    # This is item whitelist, basically. If you don't want a whitelist, just leave this empty. If you want a whitelist, fill it with items you want. Style should be 'modid:item'
    S:itemWhitelist <epicfight:greatsword  （**After adding the weapon in the game does not take effect, is my format wrong?**）
     >

**Comment by KenyMylankca** [comment]
no no no no no no don't do it like that. you MUST add new lines into the itemWhitelist section. like this:

# This is item whitelist, basically. If you don't want a whitelist, just leave this empty. If you want a whitelist, fill it with items you want. Style should be 'modid:item'
    S:itemWhitelist <
         epicfight:greatsword
     >

**Comment by ainlzj** [comment]
OK, thank you for your help
