### ISSUE TITLE
Rarity system not working properly - Enhanced armaments 1.12.2

### ISSUE THREAD

**Issue by edgaradr223** [KenyMylankca/EnhancedArmaments#37]
Hello guys, i hope somebody can help me out with this issue because i really  really like this mod, rarity system is apparently not working, i mean ... armors and weapons are getting the rarity rank (basic, uncommon, legendary, etc.) but the multipliers for attack damage are not being applied, for example (diamond sword with basic rank has 10 atk and legendary or ancient diamond sword has 10 atk too), i added different multipliers in the config file and nothing seems to work, i have tried like 6 different versions of the mod but no good results, is there something i can do to fix it?

edit: i found out that the attack is actually increasing, but i cant see the tooltip of +3 attack (depending rarity) on the weapons, it still shows diamond sword with 7 atk even if it is a legendary weapon, ive seen some showcases on youtube and i can see they have the tooltip activated, is this an error?

**Comment by imsuckincoding** [comment]
Just change your language on english

**Comment by edgaradr223** [comment]
worked, thank you, also, is there a way i could translate your mod to make the tooltip work in spanish language?

**Comment by KenyMylankca** [comment]
no it cant be translated due to tooltip system. sorry

**Comment by edgaradr223** [comment]
ty
