### ISSUE TITLE
Use EnumHand Instead of MainHand

### ISSUE THREAD

**Issue by Darkmega18** [KenyMylankca/EnhancedArmaments#5]
https://github.com/SanAndreasP/BetterCombatRebirth/issues/3

I'm testing the two mods for my modpack and have found the following issues as I described in the linked issue thread. Please take some time and see if you can work out something to make the two work. it'd be awesome if they could work together and produce their effects etc separately. :)

**Comment by KenyMylankca** [comment]
whats the problem/issue if together installed?

**Comment by Darkmega18** [comment]
Firstly, only the weapon in the main hand gains experience even if kills are done with weapon in off hand. 

secondly, any effects that should be applied by main hand weapon are instead applied by offhand attack while offhanded attack's abilities are ignored.

**Comment by KenyMylankca** [comment]
hmmm.. but these things not happening when you unuse the other mod, right?

**Comment by KenyMylankca** [comment]
oops, no, it always happening. it's EA's fault. gonna fix it.

**Comment by Darkmega18** [comment]
alrighty thanks. :D

**Comment by KenyMylankca** [comment]
can you give an example about the item in your offhand? only bow? or what else?

**Comment by Darkmega18** [comment]
I tested it with swords primarily. or sword/weapon equivalents from like minestuck mod. Since picks etc don't have abilities and leveling. Didn't know you had bows. :o

**Comment by KenyMylankca** [comment]
~~good. because fixing bows in the offhand is pretty impossible... since it stops using after shooting the arrow, the hand that used will be counted as main hand. so... you got it~~

**Comment by KenyMylankca** [comment]
ahh my god, i just figured out a way to fix the bow in the off hand too. how smart i am... :D

**Comment by Darkmega18** [comment]
GGWP
