### ISSUE TITLE
Weapons Exceed Experience Max

### ISSUE THREAD

**Issue by 8-BrickDMG** [KenyMylankca/EnhancedArmaments#7]
When using say a sword, the experience it gains exceeds the max set. When this happens, the tool becomes useless. Error from the console in the screenshot below. This was tested in multiplayer.

![error](https://user-images.githubusercontent.com/42741844/45843639-0543e300-bd18-11e8-9757-658ad13ece73.png)

**Comment by KenyMylankca** [comment]
you mean any tool gains experience when you use it forever?(after the max level)

**Comment by KenyMylankca** [comment]
and did it crash? if it did, i fixed it.
but i can't understand thet experience level exceeding bug.

**Comment by KenyMylankca** [comment]
can you try the latest version of EA(1.2.7) on curse please? and tell me if this crash fixed, and please declare the experience bug more.

**Comment by 8-BrickDMG** [comment]
@JanneSoon Sorry, I should have explained it clearer.

This is with the scenario that I start of at 0/45 on a sword for example. I kill some Zombies and then notice my sword no longer deals any damage and the experience has changed to 47/45.

I don't crash on the server but when my sword reaches this point, the error from the screenshot is produced in the server console.

This was running on 1.2.6 in my mod pack. I will take a look at 1.2.7 some point today and get back to you.

**Comment by KenyMylankca** [comment]
Uhm, i made tests with the version 1.2.7 (built a dedicated server with only EA installed, and joined with a client that only has EA) (used swords) and couldn't reproduce the bug you tell. So it's not about EA, there should be another mod breaking something.

**Comment by 8-BrickDMG** [comment]
I tested the latest version with my mod pack and it seemed to have resolved the issue. Thanks!

**Comment by KenyMylankca** [comment]
ah im so glad. thanks
